### PR TITLE
Remove `cargo_component_bindings` crate.

### LINKED ISSUE #210: Explain why the code is not generated in the `generate!()` macro
Looking at the implementation of `cargo_component_bindings::generate!()`, it does not generate any bindings, just `include!s` them, and the code is generated using `cargo component` command in [generate_bindings](https://github.com/bytecodealliance/cargo-component/blob/60e6880ef574b5b73f1c1edd88b810e18c2f6233/src/lib.rs#L508).

This is in conflict with the macro name, its documentation and with the readme:
> Like wit-bindgen, cargo component uses a procedural macro to generate bindings. However, bindings are generated based on the resolved dependencies from Cargo.toml rather than parsing a local definition of the component's interface.

This also brings additional problems like the currently broken code completion ( #196) and the need to reconfigure rust-analyzer.

What is the reasoning behind the change? Should the macro be renamed to clarify its responsibility?

### PR DESCRIPTION
**Pull request by peterhuene**
This PR is a breaking change to `cargo-component` with the intention of improving component build time (now down to two transitive crate dependencies) and get `rust-analyzer` fully working with bindings.

It removes the `cargo_component_bindings` and `cargo_component_macro` crates. Instead of using a macro for including the generated bindings, `cargo-component` now directly writes to a `src/bindings.rs` file which is included as a submodule in `main.rs` or `lib.rs`.

Additionally, the `update` subcommand was removed as it is no longer necessary since there is no `cargo_component_bindings` crate referenced in `Cargo.toml`; the functionality to update `cargo-component` itself can simply be replaced with a `cargo install` or `cargo binstall`.

Closes #210 and #196.

### CODE REVIEW

**Comment by peterhuene** [comment]
Putting this up as a proposal for removing the `cargo_component_bindings` crate in favor of just having `cargo-component` generate the bindings source directly into the component projects.

This has the benefit of cutting down on the number of dependencies from user's component packages and also getting `rust-analyzer` to work in workspaces as there's no longer any macro that reads a file in a `target` subdirectory.

**Review by fibonacci1729 — APPROVED** [review]

**Comment by peterhuene** [comment]
In the future, I'd love for `wit-bindgen` to be capable of (optionally) generating the runtime support functions into the bindings source itself so that we can remove the `wit-bindgen` dependency from user components, but we can live with it for now.

**Comment by DougAnderson444** [comment]
Hi @peterhuene,

I'm following this PR and looking at updating to `v0.7.0`, but ran into issues until I realzied that `Cargo.toml` also has to change to:

```toml
[dependencies]
wit-bindgen = "0.16.0"

# Now this is a build dep?
[build-dependencies]
cargo-component= "0.7.0"
```

Is this right? Seems to work. The readme might need to be updated too (possibly a separate issue?)

**Comment by DougAnderson444** [comment]
Ah, it's just an upgrading issue really since I already had an existing repo. I tried `cargo component new --lib` and it confirmed we don't need the `build-dep`

**Pull request merged**
