### PR TITLE
Support building aarch64-unknown-linux-gnu binary

### PR DESCRIPTION
**Pull request by nacardin**

### CODE REVIEW

**Comment by sunfishcode** [comment]
The PR looks straightforward. Could you comment on why you marked this as a draft?

**Comment by nacardin** [comment]
> The PR looks straightforward. Could you comment on why you marked this as a draft?

As is it, the openssl-sys dep has issues cross-compiling. I've been able to get to work on my fork with `cargo-cross`.  I'll clean it up and update this PR soon. Thanks!

**Comment by nacardin** [comment]
This is ready for review now. This worked on my fork https://github.com/nacardin/cargo-component/actions/runs/8105887458.

**Review by peterhuene — APPROVED** [review]
This looks great, thanks for tackling this!

**Pull request merged**
