### PR TITLE
update to use RegistryStorage from warg

### PR DESCRIPTION
**Pull request by macovedj**
Resolves [this issue](https://github.com/bytecodealliance/cargo-component/issues/77#issuecomment-1542600794)

### CODE REVIEW

**Review by peterhuene — APPROVED** [review]

**Comment by macovedj** [comment]
Looking into the failing tests

**Comment by peterhuene** [comment]
Probably need to bump the server revision in the CI yaml.

**Comment by peterhuene** [comment]
FYI, now that warg-server can be used as a library, we should update the tests to run a server in-process and remove this extra dependency on having a warg-server on the PATH (and thus we wouldn't have to update the CI to ensure a matching server implementation).

**Comment by peterhuene** [comment]
@macovedj Thanks for fixing this!

**Pull request merged**
