### PR TITLE
Update adapter to wasmtime 14.0.3

### PR DESCRIPTION
**Pull request by fibonacci1729**

### CODE REVIEW

**Comment by peterhuene** [comment]
For my understand, as I am now generally bumping the adapter version only for major wasmtime releases and I don't see any wit changes from 14.0.0, is bumping the adapter necessary?

**Comment by pchickey** [comment]
I just confirmed, there were no changes to the adapter source code, or the wit files, between 14.0.0 and 14.0.3. I am curious why the hash changed between those releases, did rustc change as well?

**Comment by peterhuene** [comment]
The hash here is a wasmtime commit and not a hash of the adapter module, so I would expect differences between wasmtime versions.

**Comment by fibonacci1729** [comment]
@peterhuene sorry for the noise! Thanks for confirming the process!

**Comment by pchickey** [comment]
oh, right, I forgot we put the commit in there. Thanks

**Pull request closed without merging**
