### PR TITLE
Target `wasm32-wasi` by default. 

### PR DESCRIPTION
**Pull request by peterhuene**
This PR makes `cargo component` target `wasm32-wasi` by default, using a
local preview1 adapter to adapt to a preview2 version of WASI.

Closes https://github.com/bytecodealliance/cargo-component/issues/48.

### CODE REVIEW

**Comment by peterhuene** [comment]
This needs a rebase once #53 is merged.

**Comment by pchickey** [comment]
I'd recommend holding off on this until https://github.com/bytecodealliance/preview2-prototyping/issues/97 is resolved - at the moment, the adapter is broken for reactors

**Comment by peterhuene** [comment]
Thanks for the heads-up! We can hold off on this for now and I'll update our copy of the adapter when fixed.

**Comment by peterhuene** [comment]
@pchickey given the big issue, no rush on this review and we can merge it whenever we think it's a good idea (will likely need to update the adapter used before then).

**Review by pchickey — APPROVED** [review]
Looks good to me. I think we can just merge this and update the adapter later. We're going to need to update the adapter & host side of things pretty frequently as things evolve, and I don't think there is a good reason to hold this up since the adapter does work in some cases https://github.com/bytecodealliance/preview2-prototyping/pull/101 and the entire thing is known to be pretty unstable.

**Pull request merged**
